version: '3.8'

services:
  web:
    build: .
    container_name: ebidding_web
    platform: linux/arm64
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    command: npm run dev
    volumes:
      - .:/app
      - /app/node_modules

  server:
    build: .
    container_name: ebidding_server
    platform: linux/arm64
    restart: always
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - PORT=3001
      - FRONTEND_URL=http://localhost:3000
      - SERVER_URL=http://localhost
    command: npm run dev:server
    volumes:
      - .:/app
      - /app/node_modules
