version: '3.8'

services:
  web:
    build: .
    container_name: dev_eoffice_web
    platform: linux/arm64
    restart: always
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
      - phpmyadmin
      
  db:
    image: mysql:5.7
    container_name: dev_eoffice_db
    platform: linux/amd64
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bicdev
      MYSQL_USER: bicdevadmmin
      MYSQL_PASSWORD: bicdevpassword
      MYSQL_ROOT_PASSWORD: root1234
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: dev_eoffice_phpmyadmin
    platform: linux/amd64
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root1234
    depends_on:
      - db
